### ISSUE TITLE
Landing Page Ideas

### ISSUE THREAD

**Issue by Shakil-2001** [Shakil-2001/Bootcamp#3]
We need to think of a landing page design and try to get it up.

**Comment by Shakil-2001** [comment]
I was googling landing page ideas and found 2 that I liked.

1. The first was a landing page with a circle with 'radio frequency in the middle'. Instead of the radio frequency we could have current Covid cases and then a button (or right swipe) to take you to the actual map. 

2. The second was a page which takes you directly onto the map. This page could have the name along the top and tabs at the bottom to take you to stats etc. I was thinking that if we take this approach we could just leave a placeholder image in the place of the map. 

Feel free to add more ideas and we'll choose one together. The landing page does not have to look refined or perfect at the moment but needs to have some structure. 

_*rough idea of what I was thinking_
![idea-1](https://user-images.githubusercontent.com/62549762/107950470-a6d5ca00-6f8e-11eb-9382-9af450c92b21.png)
![idea-2](https://user-images.githubusercontent.com/62549762/107950471-a76e6080-6f8e-11eb-9f84-0fbdef89d550.PNG)

**Comment by Shakil-2001** [comment]
Made a super basic landing page, colours are ugly feel free to change and improve upon initial page.

**Comment by Shakil-2001** [comment]
new idea, landing page with info about corona. Daily cases, Cured, UK cases, Vaccinated. Will make creating the landing page much easier and can put in placeholder info for the time being.

**Comment by snim2** [comment]
^^^ do think about about splitting that up into iterations, maybe start with something super-simple then add more detail later
