### ISSUE TITLE
Fetch Covid-19 Data from Reliable Source

### ISSUE THREAD

**Issue by Shakil-2001** [Shakil-2001/Bootcamp#4]
We need to have access to the most basic data as an essential: 
- Daily cases
- Current Cases
- 'Recovered' Patients 
- A way to get national cases
- R number 
- Local Cases (UK)

We should use the Government Provided Covid-API: https://coronavirus.data.gov.uk/details/developers-guide#params-structure
We could also use the NHS API.

Any Additional Data is optional and should only be considered after we are able to get access to the essential data.

**Comment by snim2** [comment]
One question: when will you fetch the data, and how often?

**Comment by Shakil-2001** [comment]
Fetch the data once daily. Store the data in a csv file.

**Comment by snim2** [comment]
This might be useful: https://coronavirus.data.gov.uk/details/developers-guide
